name: Elkeid_plugin_scanner_x86_64

on:
  push:
    branches:
    - main

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        password: ${{secrets.DOCKERHUB_TOKEN}}
        username: ${{secrets.DOCKERHUB_USERNAME}}
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build
      uses: docker/build-push-action@v6
      with:
        file: docker/Dockerfile.x86_64
        push: true
        context: .
        build-args: CLAMAV_REF="0.104"
        tags: kulukami/libclamav_icm_x86_64:0.104

    - name: Build
      uses: docker/build-push-action@v6
      with:
        file: docker/Dockerfile.x86_64
        push: true
        context: .
        build-args: CLAMAV_REF="1.1"
        tags: kulukami/libclamav_icm_x86_64:1.1

    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v3
      with:
        password: ${{secrets.DOCKERHUB_TOKEN}}
        repository: kulukami/libclamav_icm_x86_64
        short-description: ${{github.event.repository.description}}
        username: ${{secrets.DOCKERHUB_USERNAME}}